application.viber-bot:
 auth-token: "48c2503931a7d075-a5784049295d1520-cca8cfc397f4d93e"
 webhook-url: "https://tstu-bot.herokuapp.com"
 name: "TvSTUStudingBot "
 avatar: "https://pp.userapi.com/c837523/v837523194/734e0/5t5IJ_BVIsQ.jpg"

logging:
  level:
    root: DEBUG

